# -*- coding: utf-8 -*-
import pyodbc
# Form implementation generated from reading ui file 'StockCategories.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(615, 351)
        self.table_stock_categories = QtWidgets.QTableWidget(Form)
        self.table_stock_categories.setGeometry(QtCore.QRect(20, 60, 531, 201))
        self.table_stock_categories.setObjectName("table_stock_categories")
        self.table_stock_categories.setColumnCount(3)
        self.table_stock_categories.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_stock_categories.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stock_categories.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stock_categories.setHorizontalHeaderItem(2, item)
        self.label_stock_categories = QtWidgets.QLabel(Form)
        self.label_stock_categories.setGeometry(QtCore.QRect(160, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_stock_categories.setFont(font)
        self.label_stock_categories.setObjectName("label_stock_categories")
        self.text_id = QtWidgets.QTextEdit(Form)
        self.text_id.setGeometry(QtCore.QRect(20, 270, 41, 31))
        self.text_id.setObjectName("text_id")
        self.text_stock_category = QtWidgets.QTextEdit(Form)
        self.text_stock_category.setGeometry(QtCore.QRect(70, 270, 361, 31))
        self.text_stock_category.setObjectName("text_stock_category")
        self.box_display_order = QtWidgets.QSpinBox(Form)
        self.box_display_order.setGeometry(QtCore.QRect(440, 270, 111, 31))
        self.box_display_order.setObjectName("box_display_order")
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(70, 310, 81, 41))
        self.button_add.setObjectName("button_add")
        self.button_update = QtWidgets.QPushButton(Form)
        self.button_update.setGeometry(QtCore.QRect(220, 310, 91, 41))
        self.button_update.setObjectName("button_update")
        self.button_delete = QtWidgets.QPushButton(Form)
        self.button_delete.setGeometry(QtCore.QRect(330, 310, 101, 41))
        self.button_delete.setObjectName("button_delete")
        self.button_cancel = QtWidgets.QPushButton(Form)
        self.button_cancel.setGeometry(QtCore.QRect(460, 310, 101, 41))
        self.button_cancel.setObjectName("button_cancel")
        self.button_mode = QtWidgets.QPushButton(Form)
        self.button_mode.setGeometry(QtCore.QRect(570, 220, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.button_mode.setFont(font)
        self.button_mode.setObjectName("button_mode")

        # Connect to Azure Database
        connection = pyodbc.connect(
            'DRIVER={ODBC Driver 17 for SQL Server};SERVER=tcp:ecm1421.database.windows.net;PORT=1433;DATABASE=NymptonFoodHub;UID=Snakehead181;PWD=Mypass@word123')
        query = "SELECT * FROM StockCategory"
        result = connection.execute(query)

        # Loop through the data in the database and add the items to the table
        for row_number, row_data in enumerate(result):
            self.table_stock_categories.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.table_stock_categories.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

        connection.close()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.table_stock_categories.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.table_stock_categories.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stock Category"))
        item = self.table_stock_categories.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Display Order"))
        self.label_stock_categories.setText(_translate("Form", "Stock Categories"))
        self.button_add.setText(_translate("Form", "Add"))
        self.button_update.setText(_translate("Form", "Update"))
        self.button_delete.setText(_translate("Form", "Delete"))
        self.button_cancel.setText(_translate("Form", "Cancel"))
        self.button_mode.setText(_translate("Form", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
